# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.4
minecraft_version_range=[1.20.4,1.20.5)

# Forge
forge_id=forge
forge_version=49.2.4
forge_version_range=[49,)

mapping_channel=official
mapping_version=1.20.4

# NeoForge
neoforge_id=neoforge
neogradle.subsystems.parchment.minecraftVersion=1.20.4
neogradle.subsystems.parchment.mappingsVersion=2024.04.14
neo_version=20.4.251
neo_version_range=[20.3,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=xiao.murdermystery
mod_id=murdermystery
mod_name=Custom Murder Mystery
mod_license=GPL-3.0 license
mod_version=0.5.5
mod_credits=XiaoColorful, XColorful
mod_authors=XiaoColorful
mod_description=Play customizable murder mystery in Minecraft

mod_issue_url=https://github.com/XColorful/Custom-Murder-Mystery/issues
mod_display_url=https://github.com/XColorful/Custom-Murder-Mystery/wiki
mod_logo_file=logo.png

pack_description=Custom Murder Mystery resources
pack_format=15

# Dependencies
battleroyale_version_range=[0.5.5,)

# CompileOnly
# battleroyale-0.5.5-forge-1.20.4.jar
battleroyale_curse_maven=curse.maven:custom-battleroyale-1277855:7956929
# battleroyale-0.5.5-neoforge1.20.4.jar
battleroyale_neoforge_curse_maven=curse.maven:custom-battleroyale-1277855:7956930